.

diff --git a/.github/workflows/sync-merge.yml b/.github/workflows/sync-merge.yml
--- a/.github/workflows/sync-merge.yml
+++ b/.github/workflows/sync-merge.yml
@@ -5,64 +5,86 @@ on:
     types: [closed]
 
 jobs:
-  try-to-merge-in-submodule-repo:
+  look-for-submodule-pr-reference:
     if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
     
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Extract PR number from description
+        id: extract-pr
+        run: |
+          # Get PR description
+          PR_DESCRIPTION=$(echo "${{ github.event.pull_request.body }}" | tr '[:upper:]' '[:lower:]')
+          # Extract URL using grep and regex
+          if [[ $PR_DESCRIPTION =~ related[[:space:]]repo2[[:space:]]pr:[[:space:]](https://github.com/mateuuszzzzz/repo2/pull/)?([0-9]+) ]]; then
+            PR_NUMBER="${BASH_REMATCH[2]}"
+            echo "Found PR number: $PR_NUMBER"
+            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
+          else
+            echo "Error: Could not find related PR URL in the description"
+            exit 1
+          fi
 
-    - name: Run a script
-      run: echo "Repo1 PR has been merged"
-
-    - name: Extract PR number from description
-      id: extract-pr
-      run: |
-        # Get PR description
-        PR_DESCRIPTION=$(echo "${{ github.event.pull_request.body }}" | tr '[:upper:]' '[:lower:]')
-        # Extract URL using grep and regex
-        if [[ $PR_DESCRIPTION =~ related[[:space:]]repo2[[:space:]]pr:[[:space:]](https://github.com/mateuuszzzzz/repo2/pull/)?([0-9]+) ]]; then
-          PR_NUMBER="${BASH_REMATCH[2]}"
-          echo "Found PR number: $PR_NUMBER"
-          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
-        else
-          echo "Error: Could not find related PR URL in the description"
-          exit 1
-        fi
-
-    - name: Merge PR in target repository
-      run: |
-        curl -L --fail \
-          -X PUT \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.MERGE_PAT_TOKEN }}" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/mateuuszzzzz/repo2/pulls/${{ steps.extract-pr.outputs.pr_number }}/merge \
-          -d '{"merge_method":"squash"}'
-  bump-submodule-commit:
-    needs: try-to-merge-in-submodule-repo
+  merge-in-submodule-repo:
+    needs: look-for-submodule-pr-reference
     runs-on: ubuntu-latest
     
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-      with:
-        ref: main
-        submodules: true
-        token: ${{ secrets.COMMIT_PAT_TOKEN }}
-      
-    - name: Bump submodule commit
-      run: |
-        git config --global user.name mateuuszzzzz
-        git config --global user.email mateusz.rajski@swmansion.com
-        git submodule update --init
-        cd Repo2
-        git checkout main
-        git pull origin main
-        cd ..
-        git add Repo2
-        git commit -m "Update Repo2 commit after merge of ${{ github.event.pull_request.number }}"
-        git push origin main
+      - name: Merge associated PR in the submodule repository
+        run: |
+          curl -L --fail \
+            -X PUT \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.MERGE_PAT_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/mateuuszzzzz/repo2/pulls/${{ needs.look-for-submodule-pr-reference.outputs['extract-pr.pr_number'] }}/merge \
+            -d '{"merge_method":"squash"}'
+      - name: Announce that automatic merge in the submodule repository has failed
+        if: ${{ failure() }}
+        run: |
+          MAIN_PR_NUMBER=${{ github.event.pull_request.number }}
+          SUBMODULE_PR_NUMBER=${{ needs.look-for-submodule-pr-reference.outputs['extract-pr.pr_number'] }}
+          AUTHOR=${{ github.event.pull_request.merged_by.login }}
+
+          # Add comment in main repository PR
+          curl -L --fail \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.MERGE_PAT_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/${{ github.repository }}/issues/${MAIN_PR_NUMBER}/comments \
+            -d "{\"body\": \"@${AUTHOR}, the automatic merge of the submodule PR https://github.com/mateuuszzzzz/repo2/pull/${SUBMODULE_PR_NUMBER} has failed. Submodule PR should be merged ASAP before next deploy cycle.\"}"
+
+          # Add comment to the submodule repo PR
+          curl -L --fail \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.MERGE_PAT_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/mateuuszzzzz/repo2/issues/${SUBMODULE_PR_NUMBER}/comments \
+            -d "{\"body\": \"@${AUTHOR}, the automatic merge triggered from the main repo PR https://github.com/mateuuszzzzz/repo1/pull/${MAIN_PR_NUMBER} has failed. This PR should be merged ASAP before next deploy cycle.\"}"
+
+  bump-submodule-commit:
+    needs: merge-in-submodule-repo
+    runs-on: ubuntu-latest
+    
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          ref: main
+          submodules: true
+          token: ${{ secrets.COMMIT_PAT_TOKEN }}
         
-        
+      - name: Bump submodule commit
+        run: |
+          git config --global user.name mateuuszzzzz
+          git config --global user.email mateusz.rajski@swmansion.com
+          git submodule update --init
+          cd Repo2
+          git checkout main
+          git pull origin main
+          cd ..
+          git add Repo2
+          git commit -m "Update Repo2 commit after merge of ${{ github.event.pull_request.number }}"
+          git push origin main
